### ISSUE TITLE
Failed to load error with Polyphemus II

### ISSUE THREAD

**Issue by pgatt** [wlaub/GreenCathedral_vcv#1]
Hi there, 
Not sure if you want testers yet, but opening the module browser with this plugin installed raises this error:
![Screen Shot 2022-12-19 at 8 35 09 pm](https://user-images.githubusercontent.com/25679/208394233-e9614017-15d6-4a28-99e9-65a8bc557e66.png)

**Comment by wlaub** [comment]
It'll be a bit before it's ready for release, but it's also true that I forgot to commit that file. Fixed
